version: "3"

services:
  postgres:
    image: postgres:9.6
    environment: 
      POSTGRES_PASSWORD: PGPASS
    volumes:
      - drupal-data:/var/lib/postgresql/data


  drupal:
    build:
      context: .
      dockerfile: drupal.Dockerfile
    ports: 
      - '8080:80'

    links: 
      - postgres

    volumes:
      - sites:/var/www/html/sites  
      - modules:/var/www/html/modules
      - themes:/var/www/html/themes
      - profiles:/var/www/html/profiles


volumes:
  sites:
  modules:
  themes:
  profiles:
  drupal-data:


