# -*- mode: ruby -*-
# vi: set ft=ruby :

##################################
####    KUBERNETES SERVERS   #####
##################################
#
# 1x master server
# 2x application server
# 1x database SERVER
# 1x loadbalancer
#

$change_ssh_keys = <<-SCRIPT
  ssh-keygen -t rsa -N "" -f /home/vagrant/.ssh/id_rsa
  cp /home/vagrant/.ssh/id_rsa.pub /shared_data/control.pub
SCRIPT


$install_ansible = <<-SCRIPT
  #echo 'Acquire::http::Proxy "http://proxy.wincor-nixdorf.com:81/ "; ' > /etc/apt/apt.conf.d/30proxy
  sudo apt update
  sudo apt install -y software-properties-common
  sudo apt-add-repository ppa:ansible/ansible
  sudo apt update
  sudo apt install -y ansible
SCRIPT

Vagrant.configure("2") do |config|
  # Box Settings
  config.vm.provision "shell", inline: "echo Kubernetes VM configuration"
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false


  # Network settings
  # config.vm.network "private_network", ip: "192.168.56.100"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "public_network"

  # Folder settings
  # config.vm.synced_folder "c:/Software/VM_Shared_folder", "/vagrant_data"


  #Creating MASTER NODE
  config.vm.define "ansible-control" do |control|
    control.vm.hostname = "ansible-control"

    # Povider settings
  	control.vm.provider :virtualbox do |vb|
          vb.name = "ansible-control"
          vb.memory = 1024
      		vb.cpus =  1
          vb.gui = false
          vb.customize ["modifyvm", :id, "--usb", "off"]
          vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
          vb.customize ["modifyvm", :id, "--draganddrop", "disabled"]
          vb.memory = 1024
  		    vb.cpus =  1
      end

  	#Network settings
  	control.vm.network "private_network", ip: "192.168.56.70"

  	#Folder settings
  	control.vm.synced_folder "c:\\temp", "/shared_data"

    #Setup SSH keys
    control.vm.provision "shell", inline: $install_ansible

  end


  #LOADBALLANCER
  config.vm.define "ansible-loadbalancer" do |lb|
    lb.vm.hostname = "ansible-loadballancer"

    # Povider settings
  	lb.vm.provider :virtualbox do |vb|
        vb.name = "ansible-loadbalancer"
    		vb.memory = 512
    		vb.cpus =  1
        vb.gui = false
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
        vb.customize ["modifyvm", :id, "--draganddrop", "disabled"]
    end

    #Folder settings
  	lb.vm.synced_folder "c:\\temp", "/shared_data"

    lb.vm.network "private_network", ip: "192.168.56.71"
    #lb.vm.provision :shell, inline: 'cat /shared_data/control.pub >> /home/vagrant/.ssh/authorized_keys'
  end


  #APPLICATION 1
  config.vm.define "ansible-application1" do |appl|
    appl.vm.hostname = "ansible-application1"

    # Povider settings
  	appl.vm.provider :virtualbox do |vb|
      vb.name = "ansible-application1"
  		vb.memory = 512
  		vb.cpus =  1
      vb.gui = false
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--draganddrop", "disabled"]
    end

    #Folder settings
  	appl.vm.synced_folder "c:\\temp", "/shared_data"

    appl.vm.network "private_network", ip: "192.168.56.72"
    #appl.vm.provision :shell, inline: 'cat /shared_data/control.pub >> /home/vagrant/.ssh/authorized_keys'
  end



  #APPLICATION 2
  config.vm.define "ansible-application2" do |appl|
    appl.vm.hostname = "ansible-application2"

    # Povider settings
  	appl.vm.provider :virtualbox do |vb|
      vb.name = "ansible-application2"
  		vb.memory = 512
  		vb.cpus =  1
      vb.gui = false
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--draganddrop", "disabled"]
    end

    #Folder settings
  	appl.vm.synced_folder "c:\\temp", "/shared_data"

    appl.vm.network "private_network", ip: "192.168.56.74"
    #appl.vm.provision :shell, inline: 'cat /shared_data/control.pub >> /home/vagrant/.ssh/authorized_keys'
  end


  #DATABASE
  config.vm.define "ansible-database" do |db|
    db.vm.hostname = "ansible-database"

    # Povider settings
  	db.vm.provider :virtualbox do |vb|
      vb.name = "ansible-database"
  		vb.memory = 512
  		vb.cpus =  1
      vb.gui = false
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--draganddrop", "disabled"]
    end

    #Folder settings
  	db.vm.synced_folder "c:\\temp", "/shared_data"

    db.vm.network "private_network", ip: "192.168.56.73"
    #db.vm.provision :shell, inline: 'cat /shared_data/control.pub >> /home/vagrant/.ssh/authorized_keys'
  end

end
