version: '3.7'

services:
  webserver:
    image: php:7.0.32-apache
    container_name: webserver
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./html:/var/www/html

  database:
    image: mysql:5.6.41
    container_name: database
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=my_pass
    volumes:
      - ./db-data:/var/lib/mysql

#volumes:
#  db-data:
