---
# tasks file for apache2
- name: Install components
  apt:
    pkg: "{{ packages }}"
    state: present
    cache_valid_time: 18000
  vars:
    packages:
      - apache2
      - libapache2-mod-wsgi

- name: ensure mod_wsgi enabled
  apache2_module: state=present name=wsgi
  notify: restart apache2

- name: deactivate default apache site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache2

- name: ensure apache2 is started
  service: name=apache2 state=started enabled=yes

